// Generated by CoffeeScript 1.9.3
(function() {
  var Q, baseDir, cheerio, download, extractFileLink, fetchList, fs, http, i, iconv, index, log4js, logger, path, plan, processListContent;

  path = require('path');

  log4js = require('log4js');

  http = require('http');

  iconv = require('iconv-lite');

  cheerio = require('cheerio');

  fs = require("fs");

  Q = require('q');

  baseDir = path.join(path.dirname(__filename), "../../../");

  log4js.configure({
    appenders: [
      {
        type: 'console'
      }, {
        type: 'file',
        filename: baseDir + '/logs/jita8/fetch_gtp.log'
      }
    ]
  });

  logger = log4js.getLogger();

  fetchList = function(page) {
    var deferred;
    deferred = Q.defer();
    logger.info("Fetching page " + page);
    http.get("http://jitapu.jita8.com/chaxun.asp?move=" + page + "&leibie=gtp", function(res) {
      var content;
      content = '';
      res.on('data', function(data) {
        return content += iconv.decode(data, "GBK");
      });
      return res.on('end', function() {
        return deferred.resolve(content);
      });
    }).on('error', function(err) {
      logger.error(err);
      return deferred.reject();
    });
    return deferred.promise.timeout(60000);
  };

  processListContent = function(content) {
    var $, ele, processors;
    $ = cheerio.load(content);
    processors = (function() {
      var i, len, ref, results;
      ref = $('td.style156 a').get();
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        ele = ref[i];
        results.push((function(ele) {
          return extractFileLink("http://jitapu.jita8.com/" + $(ele).attr('href'), $(ele).text()).spread(download)["catch"](function(err) {
            if (err != null) {
              logger.error(err);
            }
            return logger.error("Error processing:" + $(ele).attr('href'));
          });
        })(ele));
      }
      return results;
    })();
    return Q.allSettled(processors);
  };

  extractFileLink = function(link, name) {
    var deferred;
    deferred = Q.defer();
    http.get(link, function(res) {
      var content;
      content = '';
      res.on('data', function(data) {
        return content += iconv.decode(data, "GBK");
      });
      return res.on('end', function() {
        var downloadLink, match, regExp;
        regExp = /javascript:mm\('(.+?)'/;
        match = regExp.exec(content);
        if ((match != null ? match.length : void 0) !== 2) {
          deferred.reject();
          return;
        }
        downloadLink = match[1];
        return deferred.resolve([downloadLink, name]);
      });
    }).on('error', function(err) {
      logger.error(err);
      return deferred.reject();
    });
    return deferred.promise.timeout(60000);
  };

  download = function(downloadLink, name) {
    var deferred, req, requestTimer;
    deferred = Q.defer();
    logger.info("Downloading " + downloadLink);
    requestTimer = setTimeout(function() {
      req.abort();
      logger.error('Request timeout : ' + downloadLink);
      return deferred.reject();
    }, 20000);
    req = http.get(encodeURI(downloadLink), function(res) {
      var buf;
      buf = new Buffer(1024);
      res.on('data', function(data) {
        return buf = Buffer.concat([buf, data]);
      });
      return res.on("end", function() {
        var outputPath;
        clearTimeout(requestTimer);
        outputPath = path.join(baseDir, "data", "jita8", "gtp", name + ".rar");
        fs.writeFileSync(outputPath, buf);
        return deferred.resolve();
      });
    }).on('error', function(err) {
      logger.error(err);
      return deferred.reject();
    });
    return deferred.promise.timeout(60000);
  };

  plan = Q();

  for (index = i = 1131; i <= 1422; index = ++i) {
    plan = plan.then(fetchList.bind(null, index)).then(processListContent)["catch"](function(err) {
      if (err != null) {
        return logger.error(err);
      }
    });
  }

}).call(this);
